import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Divine Store</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://drive.google.com/uc?export=view&id=1JRCUEQyb0W_1uxNvxe0vI5QSiieuSbKl"
        />
      </Head>

      <main className={styles.main}>hello World!</main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src="https://drive.google.com/uc?export=view&id=1JRCUEQyb0W_1uxNvxe0vI5QSiieuSbKl"
              alt="Vercel Logo"
              width={50}
              height={50}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
